## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [16]:
import torch
import torch.nn as nn
from collections import OrderedDict

# Define the binary addition database
x_train = torch.Tensor([[0, 0], [0, 1], [1, 0], [1, 1]])
y_train = torch.Tensor([[0, 0], [0, 1], [0, 1], [1, 0]])

# Network 1
# Define the model architecture
# Activation function: sigmoid
# Arhitecture: 2 input neurons, 2 hidden neurons, 1 output neuron
# Loss function: Mean squared error
model1 = nn.Sequential(OrderedDict([
            ('fc1', nn.Linear(2, 2)),   
            ('sigmoid1', nn.Sigmoid()),          
            ('fc2', nn.Linear(2, 2)),          
            ('linear1', nn.Identity())        ]))

# Define the loss function and optimizer
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model1.parameters(), lr=0.7)

# Train the model
for epoch in range(1000):
  # Forward pass
  y_pred = model1(x_train)

  # Compute loss
  loss = loss_fn(y_pred, y_train)

  # Zero gradients, backward pass, and update weights
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

# Network 2
# Define the model architecture
# Activation function: sigmoid
# Arhitecture: 2 input neuron, 3 hidden neurons, 1 output neuron
# Loss function: Mean squared error
model2 = nn.Sequential(OrderedDict([
          ('fc1', nn.Linear(2, 3)),
          ('sigmoid1', nn.Sigmoid()),
          ('fc2', nn.Linear(3, 2)),
          ('linear1', nn.Identity())
        ]))

# Define the loss function and optimizer
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model2.parameters(), lr=0.7)

# Train the model
for epoch in range(1000):
  # Forward pass
  y_pred = model2(x_train)

  # Compute loss
  loss = loss_fn(y_pred, y_train)

  # Zero gradients, backward pass, and update weights
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

# Network 3
# Define the model architecture
# Activation function: ReLU
# Arhitecture: 2 input neurons, 2 hidden neurons, 1 output neurons
# Loss functions: Mean Squared error
model3 = nn.Sequential(OrderedDict([
          ('fc1', nn.Linear(2, 3)),
          ('relu1', nn.ReLU()),
          ('fc2', nn.Linear(3, 2)),
          ('linear1', nn.Identity())
        ]))

# Define the loss function and optimizer
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model3.parameters(), lr=0.7)

# Train the model
for epoch in range(1000):
  # Forward pass
  y_pred = model3(x_train)

  # Compute loss
  loss = loss_fn(y_pred, y_train)

  # Zero gradients, backward pass, and update weights
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

# Evaluate the models and get the best one
x_test = torch.Tensor([[0, 0], [0, 1], [1, 0], [1, 1]])
y_test = torch.Tensor([[0, 0], [0, 1], [0, 1], [1, 0]])

best_model = None
best_loss = float('inf')

i = 1
best_network = -1
for model in [model1, model2, model3]:
    with torch.no_grad():
        y_pred = model(x_test)
        test_loss = loss_fn(y_pred, y_test).item()
    
    print(f'Network {i} ')
    print('Test loss:', test_loss)
    print('Predictions:', y_pred.round().tolist())
    print('\n')
    if test_loss < best_loss:
        best_model = model
        best_loss = test_loss
        best_network = i
    
    i += 1

print(f'Network {best_network}: ')
# Display the weights for each layer of the best model
for name, param in best_model.named_parameters():
    print(name, param)


Network 1 
Test loss: 7.689374115216197e-08
Predictions: [[-0.0, -0.0], [0.0, 1.0], [-0.0, 1.0], [1.0, -0.0]]


Network 2 
Test loss: 2.0662780286784255e-07
Predictions: [[-0.0, -0.0], [0.0, 1.0], [-0.0, 1.0], [1.0, -0.0]]


Network 3 
Test loss: 2.5801977741879423e-12
Predictions: [[0.0, -0.0], [0.0, 1.0], [0.0, 1.0], [1.0, -0.0]]


Network 3: 
fc1.weight Parameter containing:
tensor([[ 0.9367, -0.9027],
        [ 0.3140,  1.0506],
        [-1.1405,  1.0442]], requires_grad=True)
fc1.bias Parameter containing:
tensor([ 0.0527, -0.2811, -0.0302], requires_grad=True)
fc2.weight Parameter containing:
tensor([[-0.0325,  0.9239, -0.7028],
        [ 1.0687, -0.0336,  1.0673]], requires_grad=True)
fc2.bias Parameter containing:
tensor([ 0.0017, -0.0563], requires_grad=True)
